---

- name: Configration tasks
  tags:
    - chronyd_config
    - chronyd
  become: true
  block:
    - name: Merge daemon configration
      ansible.builtin.set_fact:
        chronyd_daemon_config_merged: "{{ chronyd_daemon_config_default | ansible.builtin.combine(chronyd_daemon_config_options, recursive=True) }}"
    - name: Merge server configration
      ansible.builtin.set_fact:
        chronyd_server_config_merged: "{{ chronyd_server_config_default | ansible.builtin.combine(chronyd_server_config_options, recursive=True) }}"

    - name: Debug variables
      ansible.builtin.include_tasks: debug/config.yml
      when: chronyd_debug is defined and chronyd_debug

    - name: Generate daemon config file
      ansible.builtin.template:
        src: chrony.j2
        dest: "{{ chronyd_daemon_config_file }}"
        owner: root
        group: root
        mode: 0644
      notify: Restart chronyd service
    - name: Generate server config file
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: "{{ chronyd_config_file }}"
        owner: root
        group: root
        mode: 0644
      notify: Restart chronyd service
