---

- name: Install tasks
  tags:
    - chronyd_install
    - chronyd
  become: true
  block:
  - name: Install chronyd package
    when: ansible_os_family == 'Debian'
    ansible.builtin.apt:
      name: "{{ chronyd_package_name }}"
      update_cache: true
      state: "{{ chronyd_package_ensure }}"
  - name: Install chronyd package
    when: ansible_os_family == 'RedHat'
    ansible.builtin.yum:
      name: "{{ chronyd_package_name }}"
      state: "{{ chronyd_package_ensure }}"
