---

- name: Install tasks
  tags:
    - chronyd_install
    - chronyd
  become: true
  block:
  - name: Update APT package index files # subtle
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 1800
    when: ansible_os_family == 'Debian'
  - name: Install chronyd package
    ansible.builtin.package:
      pkg: ["{{ item }}"]
      state: "{{ chronyd_package_ensure }}"
    with_items: "{{ chronyd_package_name }}"
