---

- include_tasks: install.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7

- include_tasks: config.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7

- include_tasks: service.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7
