---

- name: Service tasks
  tags:
    - chronyd_service
    - chronyd
  become: true
  block:
    - name: Manage service
      ansible.builtin.service:
        name: "{{ chronyd_service_name }}"
        state: "{{ chronyd_service_ensure }}"
        enabled: "{{ chronyd_service_enable }}"
      when: not ansible_check_mode
